"""
PDF Generation Service for Meal Plans
"""
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO
from datetime import datetime
from typing import Dict


class PDFService:
    """Generate PDF documents for meal plans"""

    @staticmethod
    def generate_meal_plan_pdf(meal_plan_data: Dict) -> BytesIO:
       
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                                rightMargin=72, leftMargin=72,
                                topMargin=72, bottomMargin=18)

        # Container for the 'Flowable' objects
        elements = []

        # Define styles
        styles = getSampleStyleSheet()

        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#D90000'),
            spaceAfter=30,
            alignment=TA_CENTER
        )

        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#D90000'),
            spaceAfter=12,
            spaceBefore=12
        )

        normal_style = styles['Normal']
        normal_style.fontSize = 11

        # Title
        title = Paragraph(
            f"<b>7-Day Meal Plan for {meal_plan_data.get('patient_name', 'Patient')}</b>",
            title_style
        )
        elements.append(title)
        elements.append(Spacer(1, 12))

        # Metadata
        metadata_text = f"""
        <b>Generated:</b> {datetime.now().strftime('%B %d, %Y')}<br/>
        <b>Daily Caloric Target:</b> {meal_plan_data.get('caloric_needs', 1800)} kcal<br/>
        <b>Model Used:</b> {meal_plan_data.get('model_used', 'ML Model')}
        """
        elements.append(Paragraph(metadata_text, normal_style))
        elements.append(Spacer(1, 20))

        # Meal Plan
        elements.append(Paragraph("<b>Weekly Meal Schedule</b>", heading_style))

        meal_plan = meal_plan_data.get('meal_plan', {})
        for day, meals in meal_plan.items():
            # Day header
            day_para = Paragraph(f"<b>{day}</b>", normal_style)
            elements.append(day_para)

            # Meals table
            meal_data = [
                ['Breakfast:', meals.get('breakfast', 'N/A')],
                ['Lunch:', meals.get('lunch', 'N/A')],
                ['Dinner:', meals.get('dinner', 'N/A')],
            ]

            meal_table = Table(meal_data, colWidths=[1.5*inch, 4.5*inch])
            meal_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#D90000')),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ]))

            elements.append(meal_table)
            elements.append(Spacer(1, 12))

        # Shopping List
        elements.append(Spacer(1, 20))
        elements.append(Paragraph("<b>Shopping List</b>", heading_style))

        shopping_list = meal_plan_data.get('shopping_list', [])
        for item in shopping_list:
            bullet = Paragraph(f"• {item}", normal_style)
            elements.append(bullet)

        # Health Tips
        elements.append(Spacer(1, 20))
        elements.append(Paragraph("<b>Health Tips</b>", heading_style))

        tips = meal_plan_data.get('tips', [])
        for tip in tips:
            tip_para = Paragraph(f"• {tip}", normal_style)
            elements.append(tip_para)

        # Footer
        elements.append(Spacer(1, 30))
        footer_style = ParagraphStyle(
            'Footer',
            parent=normal_style,
            fontSize=9,
            textColor=colors.grey,
            alignment=TA_CENTER
        )
        footer = Paragraph(
            "Generated by Mzee Chakula - AI-Powered Nutrition Assistant<br/>"
            "For educational purposes only. Consult a healthcare professional for personalized advice.",
            footer_style
        )
        elements.append(footer)

        # Build PDF
        doc.build(elements)

        # Reset buffer position
        buffer.seek(0)
        return buffer


# Singleton instance
_pdf_service = None

def get_pdf_service() -> PDFService:
    """Get or create PDF service singleton"""
    global _pdf_service
    if _pdf_service is None:
        _pdf_service = PDFService()
    return _pdf_service
